"""create units table

Revision ID: 32cfb9a48a7d
Revises: f166860421d8
Create Date: 2026-07-15 15:46:29.889295

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "32cfb9a48a7d"
down_revision: Union[str, None] = "f166860421d8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "units",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("unit_number", sa.String(length=50), nullable=False),
        sa.Column("floor", sa.Integer(), nullable=False),
        sa.Column(
            "unit_type",
            sa.Enum("SHOP", "OFFICE", "RESTAURANT", "LODGE", "APARTMENT", name="unittype"),
            nullable=False,
        ),
        sa.Column("bedrooms", sa.Integer(), nullable=True),
        sa.Column("size", sa.Float(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "AVAILABLE",
                "OWNER_OCCUPIED",
                "TENANT_OCCUPIED",
                "UNDER_MAINTENANCE",
                name="unitstatus",
            ),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_units_unit_number"), "units", ["unit_number"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_units_unit_number"), table_name="units")
    op.drop_table("units")
    # Autogenerate does not drop the native PostgreSQL enum types created by
    # upgrade(); drop them explicitly so a later re-upgrade doesn't fail with
    # "type already exists".
    sa.Enum(name="unitstatus").drop(op.get_bind(), checkfirst=False)
    sa.Enum(name="unittype").drop(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###
