"""create tenants table

Revision ID: 8eab9c65a8c1
Revises: 9cc8eb46d830
Create Date: 2026-08-19 21:33:21.139252

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8eab9c65a8c1"
down_revision: Union[str, None] = "9cc8eb46d830"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tenants",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("phone", sa.String(length=20), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("national_id", sa.String(length=50), nullable=True),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        # Autogenerate emitted this constraint with no name; an unnamed
        # constraint cannot be referenced later (e.g. to drop or alter it),
        # so give it an explicit name — same convention as
        # fk_owners_created_by_users in bd4aa67dd473 and
        # fk_units_created_by_users in 9cc8eb46d830.
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name="fk_tenants_created_by_users",
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tenants")
    # ### end Alembic commands ###
