"""add created_by to units

Revision ID: 9cc8eb46d830
Revises: bd4aa67dd473
Create Date: 2026-08-12 15:19:27.106641

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9cc8eb46d830"
down_revision: Union[str, None] = "bd4aa67dd473"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("units", sa.Column("created_by", sa.Integer(), nullable=True))
    # Autogenerate emitted create_foreign_key(None, ...); an unnamed constraint
    # cannot be dropped in downgrade(), so give it an explicit name — same
    # convention as fk_units_owner_id_owners in b26b44352c21 and
    # fk_owners_created_by_users in bd4aa67dd473.
    op.create_foreign_key(
        "fk_units_created_by_users",
        "units",
        "users",
        ["created_by"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_units_created_by_users", "units", type_="foreignkey")
    op.drop_column("units", "created_by")
    # ### end Alembic commands ###
