"""create owners table and add owner_id to units

Revision ID: b26b44352c21
Revises: 32cfb9a48a7d
Create Date: 2026-07-17 19:53:03.168783

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b26b44352c21"
down_revision: Union[str, None] = "32cfb9a48a7d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "owners",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("phone", sa.String(length=20), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("national_id", sa.String(length=50), nullable=True),
        sa.Column("type", sa.Enum("INDIVIDUAL", "COMPANY", name="ownertype"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("units", sa.Column("owner_id", sa.Integer(), nullable=False))
    # Autogenerate emitted create_foreign_key(None, ...); an unnamed constraint
    # cannot be dropped in downgrade(), so give it an explicit name.
    op.create_foreign_key("fk_units_owner_id_owners", "units", "owners", ["owner_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_units_owner_id_owners", "units", type_="foreignkey")
    op.drop_column("units", "owner_id")
    op.drop_table("owners")
    # Autogenerate does not drop the native PostgreSQL enum type created by
    # upgrade(); drop it explicitly so a later re-upgrade doesn't fail with
    # "type already exists".
    sa.Enum(name="ownertype").drop(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###
