"""add created_by to owners

Revision ID: bd4aa67dd473
Revises: d56bfe32591a
Create Date: 2026-08-12 15:02:53.464638

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bd4aa67dd473"
down_revision: Union[str, None] = "d56bfe32591a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("owners", sa.Column("created_by", sa.Integer(), nullable=True))
    # Autogenerate emitted create_foreign_key(None, ...); an unnamed constraint
    # cannot be dropped in downgrade(), so give it an explicit name — same
    # convention as fk_units_owner_id_owners in b26b44352c21.
    op.create_foreign_key(
        "fk_owners_created_by_users",
        "owners",
        "users",
        ["created_by"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_owners_created_by_users", "owners", type_="foreignkey")
    op.drop_column("owners", "created_by")
    # ### end Alembic commands ###
