"""create charges table

Revision ID: c596992e1b11
Revises: 8eab9c65a8c1
Create Date: 2026-08-24 14:37:38.125949

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c596992e1b11"
down_revision: Union[str, None] = "8eab9c65a8c1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "charges",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("unit_id", sa.Integer(), nullable=False),
        sa.Column("owner_id", sa.Integer(), nullable=True),
        sa.Column("tenant_id", sa.Integer(), nullable=True),
        sa.Column(
            "category",
            sa.Enum("RENT", "WATER", "SERVICE_CHARGE", "MOVE_OUT", name="chargecategory"),
            nullable=False,
        ),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("percentage", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("period", sa.Date(), nullable=False),
        sa.Column("is_cancelled", sa.Boolean(), nullable=False),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        # Autogenerate emitted all four of these constraints with no name; an
        # unnamed constraint cannot be referenced later (e.g. to drop or alter
        # it), so each is given an explicit name — same convention as
        # fk_units_owner_id_owners in b26b44352c21 and
        # fk_tenants_created_by_users in 8eab9c65a8c1.
        sa.ForeignKeyConstraint(
            ["unit_id"],
            ["units.id"],
            name="fk_charges_unit_id_units",
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["owners.id"],
            name="fk_charges_owner_id_owners",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name="fk_charges_tenant_id_tenants",
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name="fk_charges_created_by_users",
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("charges")
    # Autogenerate does not drop the native PostgreSQL enum type created by
    # upgrade(); drop it explicitly so a later re-upgrade doesn't fail with
    # "type already exists". Same cleanup as unittype/unitstatus in
    # 32cfb9a48a7d and ownertype in b26b44352c21.
    sa.Enum(name="chargecategory").drop(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###
