"""create payments table

Revision ID: d4970f39e785
Revises: c596992e1b11
Create Date: 2026-08-31 15:31:01.821120

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d4970f39e785"
down_revision: Union[str, None] = "c596992e1b11"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "payments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("charge_id", sa.Integer(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("paid_at", sa.Date(), nullable=False),
        sa.Column(
            "method", sa.Enum("MPESA", "BANK_TRANSFER", "CASH", name="paymentmethod"), nullable=True
        ),
        sa.Column("reference", sa.String(length=100), nullable=True),
        sa.Column("is_cancelled", sa.Boolean(), nullable=False),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        # Autogenerate emitted both of these foreign keys with no name; an
        # unnamed constraint cannot be referenced later (e.g. to drop or alter
        # it), so each is given an explicit name — same convention as
        # fk_charges_unit_id_units in c596992e1b11 and
        # fk_units_owner_id_owners in b26b44352c21.
        sa.ForeignKeyConstraint(
            ["charge_id"],
            ["charges.id"],
            name="fk_payments_charge_id_charges",
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name="fk_payments_created_by_users",
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_payments_one_active_per_charge",
        "payments",
        ["charge_id"],
        unique=True,
        postgresql_where=sa.text("is_cancelled = false"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_payments_one_active_per_charge",
        table_name="payments",
        postgresql_where=sa.text("is_cancelled = false"),
    )
    op.drop_table("payments")
    # Autogenerate does not drop the native PostgreSQL enum type created by
    # upgrade(); drop it explicitly so a later re-upgrade doesn't fail with
    # "type already exists". Same cleanup as chargecategory in c596992e1b11
    # and unittype/unitstatus in 32cfb9a48a7d.
    sa.Enum(name="paymentmethod").drop(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###
