"""add partial unique index for single company owner

Revision ID: d56bfe32591a
Revises: b63ef847e9c6
Create Date: 2026-07-20 15:53:30.729918

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "d56bfe32591a"
down_revision: Union[str, None] = "b63ef847e9c6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_owners_single_company",
        "owners",
        ["type"],
        unique=True,
        postgresql_where=sa.text("type = 'COMPANY'"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_owners_single_company",
        table_name="owners",
        postgresql_where=sa.text("type = 'COMPANY'"),
    )
    # ### end Alembic commands ###
